name: Keep HuggingFace Space Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  ping-space:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up Space
        run: |
          curl -L --connect-timeout 10 --max-time 15 \
            https://bwenck-bc351-ai-tutor.hf.space/ > /dev/null 2>&1 || true
